### ISSUE TITLE
Can't run v3 in my project.

### ISSUE THREAD

**Issue by Xuhao** [ld-x/last-draft#40]
After use it according to readme mentioned, I got some errors:

```
Module not found: 'draft-convert'
Module not found: 'draft-js-dnd-plugin'
```

I saw `draft-convert` is **peerDependencies**, so I add it to my project;  but how about `draft-js-dnd-plugin`?

**Comment by rafaelespinoza** [comment]
I'm getting this too and am wondering about the `draft-js-dnd-plugin` as well. This component, [`src/components/Editor`](https://github.com/vacenz/last-draft/blob/master/src/components/Editor.js#L23), actually requires `draft-js-drag-n-drop-plugin` instead.

**Comment by svnm** [comment]
Check out the dependencies [here](https://github.com/vacenz/last-draft/blob/master/package.json), it has been renamed to `draft-js-drag-n-drop-plugin` in rc2.
Take a look at the example repo for a guide
https://github.com/vacenz/last-draft-example-v3
